/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pratikum25062026;

import javax.swing.JOptionPane;
public class FormTravelBus extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormTravelBus.class.getName());

    /**
     * Creates new form FormTravelBus
     */
    public FormTravelBus() {
        initComponents();
        txtHarga.setEditable(false);
        txtTotal.setEditable(false);
        txtDiskon.setEditable(false);
        txtBayar.setEditable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btnGrupTujuan = new javax.swing.ButtonGroup();
        lblTujuan = new javax.swing.JLabel();
        lblJudul = new javax.swing.JLabel();
        lblKelas = new javax.swing.JLabel();
        txtHarga = new javax.swing.JTextField();
        rbBkt = new javax.swing.JRadioButton();
        rbPar = new javax.swing.JRadioButton();
        rbSolok = new javax.swing.JRadioButton();
        cbKelas = new javax.swing.JComboBox<>();
        btnHarga = new javax.swing.JButton();
        lblJumlah = new javax.swing.JLabel();
        txtJumlah = new javax.swing.JTextField();
        btnHitung = new javax.swing.JButton();
        lblTotal = new javax.swing.JLabel();
        lblDiskon = new javax.swing.JLabel();
        lblBayar = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        txtDiskon = new javax.swing.JTextField();
        btnKeluar = new javax.swing.JButton();
        txtBayar = new javax.swing.JTextField();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTujuan.setText("Pilihan Tujuan");

        lblJudul.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblJudul.setText("FORM PEMBELIAN TIKET BUS NUSANTARA");

        lblKelas.setText("Pilihan Kelas");

        txtHarga.addActionListener(this::txtHargaActionPerformed);

        btnGrupTujuan.add(rbBkt);
        rbBkt.setText("Bukittinggi");

        btnGrupTujuan.add(rbPar);
        rbPar.setText("Pariaman");

        btnGrupTujuan.add(rbSolok);
        rbSolok.setText("Solok");

        cbKelas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilihan Kelas", "Ekonomi", "Bisnis", "Eksekutif" }));

        btnHarga.setBackground(new java.awt.Color(153, 255, 153));
        btnHarga.setText("Harga 1 Tiket");
        btnHarga.addActionListener(this::btnHargaActionPerformed);

        lblJumlah.setText("Jumlah Tiket");

        txtJumlah.addActionListener(this::txtJumlahActionPerformed);

        btnHitung.setText("Hitung");
        btnHitung.addActionListener(this::btnHitungActionPerformed);

        lblTotal.setText("Total Harga Pembalian");

        lblDiskon.setText("Diskon");

        lblBayar.setText("Total Pembayaran");

        txtTotal.addActionListener(this::txtTotalActionPerformed);

        txtDiskon.addActionListener(this::txtDiskonActionPerformed);

        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(this::btnKeluarActionPerformed);

        txtBayar.addActionListener(this::txtBayarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblJudul)
                .addGap(86, 86, 86))
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblJumlah)
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lblDiskon, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblTotal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lblBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblKelas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTujuan, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(rbBkt, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cbKelas, 0, 125, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(rbSolok, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbPar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(113, 113, 113)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnHitung)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnHarga)
                                        .addGap(29, 29, 29)
                                        .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnKeluar)
                                    .addComponent(txtDiskon, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(128, 128, 128))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblJudul)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTujuan)
                    .addComponent(rbBkt)
                    .addComponent(rbSolok)
                    .addComponent(rbPar))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKelas)
                    .addComponent(cbKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHarga))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblJumlah)
                    .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHitung))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotal)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDiskon)
                    .addComponent(txtDiskon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBayar)
                    .addComponent(txtBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(btnKeluar)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHargaActionPerformed
       int kelas = (int)cbKelas.getSelectedIndex();
       
       if(!rbBkt.isSelected()&&!rbSolok.isSelected()&&!rbPar.isSelected()){
           JOptionPane.showMessageDialog(this, "Tujuan Belum Dipilih!!");
       }
       else if(cbKelas.getSelectedIndex()==0)
           JOptionPane.showMessageDialog(this, "Kelas Belum Dipilih!!");
               
       switch (kelas) {
           case 1 -> {
               if(rbBkt.isSelected())
                   txtHarga.setText("40000");
               else if(rbSolok.isSelected())
                   txtHarga.setText("25000");
               else
                   txtHarga.setText("15000");
            }
            case 2 -> {
                if(rbBkt.isSelected())
                    txtHarga.setText("75000");
                else if(rbSolok.isSelected())
                    txtHarga.setText("55000");
                else
                    txtHarga.setText("40000");
            }
            case 3 -> {
                if(rbBkt.isSelected())
                    txtHarga.setText("120000");
                else if(rbSolok.isSelected())
                    txtHarga.setText("85000");
                else
                    txtHarga.setText("60000");
            }
       }
    }//GEN-LAST:event_txtHargaActionPerformed

    private void txtJumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJumlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJumlahActionPerformed

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed

    private void txtDiskonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiskonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiskonActionPerformed

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
        int jumlah = Integer.parseInt(txtJumlah.getText());
        if(jumlah<0){
            JOptionPane.showMessageDialog(this, "Jumlah Harus Lebih Dari Nol", "Pesan Kesalahan", JOptionPane.ERROR_MESSAGE);
            txtJumlah.setText("");
            txtJumlah.requestFocus();
        }
        else{
        double harga = Double.parseDouble(txtHarga.getText());
        double total = jumlah*harga;
        double diskon = 0;
        if(jumlah>=5)
            diskon=0.1*total;
        double bayar = total-diskon;
        txtTotal.setText(Double.toString(total));
        txtDiskon.setText(Double.toString(diskon));
        txtBayar.setText(Double.toString(bayar));
        }
    }//GEN-LAST:event_btnHitungActionPerformed

    private void txtBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBayarActionPerformed
        
  
    }//GEN-LAST:event_txtBayarActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        // TODO add your handling code here: 
        System.exit(0);
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void btnHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHargaActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Field Total Pembayaran tidak bisa diubah manual");
    }//GEN-LAST:event_btnHargaActionPerformed

    
    public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(() -> {
        new FormTravelBus().setVisible(true);
    });
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGrupTujuan;
    private javax.swing.JButton btnHarga;
    private javax.swing.JButton btnHitung;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JComboBox<String> cbKelas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblBayar;
    private javax.swing.JLabel lblDiskon;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JLabel lblJumlah;
    private javax.swing.JLabel lblKelas;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTujuan;
    private javax.swing.JRadioButton rbBkt;
    private javax.swing.JRadioButton rbPar;
    private javax.swing.JRadioButton rbSolok;
    private javax.swing.JTextField txtBayar;
    private javax.swing.JTextField txtDiskon;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtJumlah;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
