/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Pratikum02072026;

import java.util.logging.Level;

/**
 *
 * @author Acer
 */
public class MenuMakanan extends javax.swing.JPanel {

    /**
     * Creates new form MenuMakanan
     */
    public MenuMakanan() {
        initComponents();
        txtNasgor.setEditable(false);
        txtSate.setEditable(false);
        txtSoto.setEditable(false);
        txtTotalNasgor.setEditable(false);
        txtTotalSate.setEditable(false);
        txtTotalSoto.setEditable(false);
        
        txtTotal.setEditable(false);
        
    }
    private MenuUtama utama;
    
    public MenuMakanan(MenuUtama utama){
        this.utama = utama;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        chkNasgor = new javax.swing.JCheckBox();
        chkSoto = new javax.swing.JCheckBox();
        chkSate = new javax.swing.JCheckBox();
        cbNasgor = new javax.swing.JComboBox<>();
        cbSoto = new javax.swing.JComboBox<>();
        cbSate = new javax.swing.JComboBox<>();
        txtNasgor = new javax.swing.JTextField();
        txtSoto = new javax.swing.JTextField();
        txtSate = new javax.swing.JTextField();
        txtTotalNasgor = new javax.swing.JTextField();
        txtTotalSate = new javax.swing.JTextField();
        txtTotalSoto = new javax.swing.JTextField();
        btnKembali = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnTotal = new javax.swing.JButton();
        txtTotal = new javax.swing.JTextField();

        jLabel1.setText("jLabel1");

        lblTotal.setText("Total");

        chkNasgor.setText("Nasi Goreng");
        chkNasgor.addActionListener(this::chkNasgorActionPerformed);

        chkSoto.setText("Soto");
        chkSoto.addActionListener(this::chkSotoActionPerformed);

        chkSate.setText("Sate");
        chkSate.addActionListener(this::chkSateActionPerformed);

        cbNasgor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8" }));
        cbNasgor.addActionListener(this::cbNasgorActionPerformed);

        cbSoto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8" }));
        cbSoto.addActionListener(this::cbSotoActionPerformed);

        cbSate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8" }));
        cbSate.addActionListener(this::cbSateActionPerformed);

        txtNasgor.setText("0");

        txtSoto.setText("0");
        txtSoto.addActionListener(this::txtSotoActionPerformed);

        txtSate.setText("0");

        txtTotalNasgor.setText("0");

        txtTotalSate.setText("0");

        txtTotalSoto.setText("0");
        txtTotalSoto.addActionListener(this::txtTotalSotoActionPerformed);

        btnKembali.setText("Kembali");
        btnKembali.addActionListener(this::btnKembaliActionPerformed);

        btnReset.setText("Reset");
        btnReset.addActionListener(this::btnResetActionPerformed);

        btnTotal.setText("Total");
        btnTotal.addActionListener(this::btnTotalActionPerformed);

        txtTotal.setText("0");
        txtTotal.addActionListener(this::txtTotalActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(txtTotalNasgor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(145, 145, 145))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkNasgor)
                            .addComponent(chkSoto)
                            .addComponent(chkSate))
                        .addGap(53, 53, 53))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnReset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnKembali))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNasgor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbSate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtTotalSate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cbNasgor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblTotal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbSoto, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTotalSoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(0, 33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkNasgor)
                    .addComponent(cbNasgor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNasgor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalNasgor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkSate)
                    .addComponent(cbSate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalSate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkSoto)
                    .addComponent(cbSoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalSoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotal)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnKembali)
                    .addComponent(btnTotal)
                    .addComponent(btnReset))
                .addContainerGap(59, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void chkNasgorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkNasgorActionPerformed
        txtNasgor.setText("10000");
    }//GEN-LAST:event_chkNasgorActionPerformed

    private void txtSotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSotoActionPerformed

    private void txtTotalSotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalSotoActionPerformed
        
    }//GEN-LAST:event_txtTotalSotoActionPerformed

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed

    private void cbNasgorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbNasgorActionPerformed
         int jumlah = (int)cbNasgor.getSelectedIndex();
       double harga = Double.parseDouble(txtNasgor.getText());
       double total=jumlah*harga;
       txtTotalNasgor.setText(Double.toString(total));
    }//GEN-LAST:event_cbNasgorActionPerformed

    private void chkSateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkSateActionPerformed
        txtSate.setText("15000");
    }//GEN-LAST:event_chkSateActionPerformed

    private void btnTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalActionPerformed
        double nasgor = Double.parseDouble(txtTotalNasgor.getText());
        double sate = Double.parseDouble(txtTotalSate.getText());
        double soto = Double.parseDouble(txtTotalSoto.getText());
        double total = nasgor + sate + soto;
        txtTotal.setText(Double.toString(total));
    }//GEN-LAST:event_btnTotalActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
         String total = txtTotal.getText();
         utama.setTotalMakanan(total);
         this.dispose();
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void chkSotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkSotoActionPerformed
        txtSoto.setText("12500");
    }//GEN-LAST:event_chkSotoActionPerformed

    private void cbSateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSateActionPerformed
         int jumlah = (int)cbSate.getSelectedIndex();
       double harga = Double.parseDouble(txtSate.getText());
       double total=jumlah*harga;
       txtTotalSate.setText(Double.toString(total));
    }//GEN-LAST:event_cbSateActionPerformed

    private void cbSotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSotoActionPerformed
        int jumlah = (int)cbSoto.getSelectedIndex();
       double harga = Double.parseDouble(txtSoto.getText());
       double total=jumlah*harga;
       txtTotalSoto.setText(Double.toString(total));
    }//GEN-LAST:event_cbSotoActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        txtNasgor.setText("0");
       txtSate.setText("0");
       txtSoto.setText("0");
       cbNasgor.setSelectedIndex(0);
       cbSate.setSelectedIndex(0);
       cbSoto.setSelectedIndex(0);
       chkNasgor.setSelected(false);
        chkSate.setSelected(false);
        chkSoto.setSelected(false);

       txtTotal.setText("0");
    }//GEN-LAST:event_btnResetActionPerformed
      /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuMakanan().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnTotal;
    private javax.swing.JComboBox<String> cbNasgor;
    private javax.swing.JComboBox<String> cbSate;
    private javax.swing.JComboBox<String> cbSoto;
    private javax.swing.JCheckBox chkNasgor;
    private javax.swing.JCheckBox chkSate;
    private javax.swing.JCheckBox chkSoto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTextField txtNasgor;
    private javax.swing.JTextField txtSate;
    private javax.swing.JTextField txtSoto;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtTotalNasgor;
    private javax.swing.JTextField txtTotalSate;
    private javax.swing.JTextField txtTotalSoto;
    // End of variables declaration//GEN-END:variables

    private void dispose() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private static class logger {

        private static void log(Level SEVERE, Object object, javax.swing.UnsupportedLookAndFeelException | java.lang.ReflectiveOperationException ex) {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }

        public logger() {
        }
    }
}
